name: AndroidBuild

on:
  push :
    branches : [ master ]

jobs:
  build-deploy:
    runs-on : ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Grant execute permissions for gradlew (macOS)
        run: chmod +x ./gradlew 

      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > /tmp/keystore.jks

      # - name: Build APK Release
      #   run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=/tmp/keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Build Bundle AAB Release
        run: ./gradlew bundleRelease -Pandroid.injected.signing.store.file=/tmp/keystore.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Check the path
        run: |
          ls -la app/build/outputs/
          ls -la app/build/outputs/bundle
          ls -la app/build/outputs/bundle/release

      - uses: actions/upload-artifact@v4
        with:
          name: android-demo
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Create service_account.json
        id: createServiceAccount
        run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Check the path
        run: |
          ls -la app/build/outputs/
          ls -la app/build/outputs/bundle
          ls -la app/build/outputs/bundle/release

      - name: Deploy to Play Store (Internal Testing)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: com.testing.firetasmiktiga
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: qa
